version: "3.7"
services:
  web:
    build: .
    ports:
      - "5050:5000"
    volumes:
      - .:/code/web
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    volumes:
      - .:/code/db
    env_file:
      - ./practica.env
    
    