version: "3.7"
services:
  web:
    build: .
    ports:
      - "${PORT_FORWARDER}:${REDIS_PORT}"
    volumes:
      - .:/practica/web
    environment:
      FLASK_ENV: "${FLASK_ENV}"
      REDIS_PASSWORD: password #"${REDIS_PASSWORD}"
      REDIS_HOST: redis #"${REDIS_HOST}"
    depends_on:
      - redis
  redis:
    image: "${IMAGE_REDIS}"
    container_name: redis
    command: ["--requirepass", "password"]
    environment:
      REDIS_PASSWORD: password #"${REDIS_PASSWORD}"
      REDIS_HOST: redis #"${REDIS_HOST}"
    volumes:
      - .:/practica/db
    
    
    