apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
  namespace: practica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  strategy: {}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis
        name: redis
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        env:
          - name: REDIS_HOST
            value: redis 
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: password
        resources: 
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 256Mi
            cpu: 200m
        volumeMounts:
          - name: redis
            mountPath: /redis
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis-pvc