apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ template "app.name" . }}-flask
spec:
  rules:
  - host: mgxruben.34.77.250.116.nip.io
    http:
      paths:
      - backend:
          serviceName: {{ template "app.name" . }}-flask
          servicePort: 5000
